# Data Loader

In [52]:
import numpy as np
import re


with open("12.txt") as f:
    data = f.read().splitlines()
    boxes = []
    tests = []
    for i, line in enumerate(data):
        if line == "":
            continue
        if re.search(r"^\d+:.*", line):
            # print(data[i+1:i+5])
            lines = [[(1 if x == "#" else 0) for x in g] for g in[list(y) for y in data[i+1:i+5]]]
            # print(lines)
            lns = np.array([np.array(x) for x in lines[:-1]])
            # print(lns)
            boxes.append(lns)
        elif re.search(r"^\d+x\d+:.*", line):
            l = [x.strip(":").split("x") for x in line.split(" ")]
            # print(l)
            tests.append((int(l[0][0]), int(l[0][1]), [int(x[0]) for x in l[1:]]))
tests[0][2]
# boxes   

[40, 40, 46, 51, 34, 42]

# Part 1

In [69]:
simple_passes = 0
fails = 0
failScores = []
failTests = []
passTests = []
deadTests = []
# for box in boxes:
#     print(box)
# passScores = []
fills = [int(sum([sum(r) for r in box])) for box in boxes]
print("fills", fills)

for x,y, scores in tests:
    totalScore = sum(scores)
    limitX = x // 3
    limitY = y // 3

    f = sum([t[0] * t[1] for t in zip(scores, fills)])
    # print("fills", f)
    if(totalScore <= limitX * limitY):
        # print("Pass")
        simple_passes += 1
        passTests.append((x,y,scores))
        # passScores.append((totalScore * 9 - x*y, x * y, limitX * limitY * 9))
    elif(f >= x * y):
        deadTests.append((x,y,scores, f))
    elif(totalScore > limitX * limitY):
        # print("Fail")
        fails += 1
        failScores.append((totalScore * 9 - x*y, x * y))
        failTests.append((x,y,scores, totalScore, limitX * limitY))
print("passes, impossible fits, fails for further examination ", simple_passes, len(deadTests), fails)
print("passTests", passTests)
print("deadTests", deadTests)
print("failTests", failTests)
# print("failScores", sorted(failScores))
# print("passScores", sorted(passScores))


fills [7, 7, 6, 5, 7, 7]
passes, impossible fits, fails for further examination  476 524 0
passTests [(41, 45, [32, 28, 30, 38, 36, 31]), (35, 48, [30, 23, 33, 31, 41, 18]), (47, 37, [33, 27, 22, 34, 33, 30]), (37, 44, [24, 24, 29, 35, 29, 27]), (40, 41, [33, 22, 28, 36, 31, 19]), (39, 39, [27, 34, 30, 23, 23, 31]), (41, 40, [30, 24, 26, 33, 28, 27]), (47, 46, [40, 38, 30, 29, 50, 37]), (40, 49, [42, 29, 35, 27, 33, 42]), (42, 43, [31, 29, 31, 37, 38, 30]), (42, 42, [27, 29, 35, 28, 40, 37]), (36, 41, [29, 25, 15, 29, 32, 25]), (48, 46, [32, 49, 36, 43, 46, 33]), (44, 40, [31, 31, 31, 31, 26, 32]), (43, 47, [31, 35, 31, 36, 31, 45]), (41, 41, [29, 31, 22, 30, 33, 23]), (42, 38, [27, 24, 21, 32, 31, 32]), (40, 46, [39, 31, 28, 38, 29, 29]), (42, 39, [31, 39, 31, 21, 29, 31]), (37, 36, [27, 26, 14, 18, 22, 36]), (45, 48, [38, 38, 45, 44, 36, 39]), (39, 47, [30, 42, 27, 31, 39, 26]), (42, 48, [40, 32, 27, 40, 38, 47]), (42, 47, [28, 43, 38, 35, 27, 39]), (40, 44, [31, 34, 22, 32, 29, 33])

## And so dear reader, since some tests pass without any fitting, and the rest all fail even if they were compressed into their minimum possible size, we must conclude this puzzle has the easy answer, which is correct. 

In [ ]:
# def getRots(box):
#     return [box, np.rot90(box, 1), np.rot90(box, 2), np.rot90(box, 3)]
# def getRotsAndFlips(box):
#     rots = getRots(box)
#     flips_h = getRots(np.fliplr(box))
#     flips_v = getRots(np.flipud(box))
#     all_transforms = rots + flips_h + flips_v
#     unique_transforms = []
#     seen_hashes = set()
#     for t in all_transforms:
#         t_hash = tuple(map(tuple, t))
#         if t_hash not in seen_hashes:
#             seen_hashes.add(t_hash)
#             unique_transforms.append(t)
#     print("number of unique transforms", len(unique_transforms))
#     return unique_transforms


# #
# boxScores = []
# for index, box in enumerate(boxes):
#     score = [0] * len(boxes)
#     score[index] = 1
#     rotsAndFlips = getRotsAndFlips(box)
#     for rotAndFlip in rotsAndFlips:
#         boxScores.append((rotAndFlip, score))


# "number of boxscores", len(boxScores)
        

number of unique transforms 8
number of unique transforms 8
number of unique transforms 2
number of unique transforms 4
number of unique transforms 4
number of unique transforms 2
(array([[1, 1, 1],
       [1, 1, 0],
       [1, 1, 0]]), [1, 0, 0, 0, 0, 0])


('number of boxscores', 28)

So now we have our box scores, which number 

In [ ]:
# from copy import copy
# def rots(box):
#     return [box, np.rot90(box), np.rot90(box, 2), np.rot90(box, 3)]
# def open_positions_sorted(arr, open_value=0):
#     """
#     Return list of (row, col) for all open_value positions,
#     sorted by distance from top-left (0, 0).
#     """
#     # Find all open positions
#     coords = np.argwhere(arr == open_value)  # shape (k, 2) [web:12][web:14]

#     if coords.size == 0:
#         return []

#     # Compute squared Euclidean distance from (0, 0) for each coord
#     # dist^2 = row^2 + col^2
#     d2 = np.sum(coords**2, axis=1)

#     # Get indices that would sort by distance
#     order = np.argsort(d2)  # [web:13]

#     # Apply ordering and convert to list of tuples
#     sorted_coords = coords[order]
#     return [tuple(map(int, rc)) for rc in sorted_coords]
# def checkvalid(box,location, grid):
#     for rot in rots(box):
#         breakup = False
#         for j in range(len(rot)):
#             for i in range(len(rot[0])):
#                 if j+location[0] >= len(grid) or i+location[1] >= len(grid[0]):
#                     breakup = True
#                     break
#                 if rot[j][i] == 1 and grid[location[0]+j][location[1]+i] == 1:
#                     breakup = True
#                     break
#             if breakup:
#                 break
#         if breakup:
#             continue
#     return not breakup
# def rotlist(l:list[np.array], n=1):
#     return [np.rot90(x, n) for x in l]
# def checkboxes(bxes,gryd):
#     results = []
#     grid = gryd.copy()
#     for bix in bxes:
#         res = True
#         for box in rots(bix):
#             success = False
#             for location in open_positions_sorted(grid):
#                 if checkvalid(box,location,grid):
#                     results.append(True)
#                     grid[location[0]:location[0]+len(box),location[1]:location[1]+len(box[0])] = box
#                     success = True
#                     break
#             if success:
#                 res=True
#                 break
#         results.append(res)
#     if 1 == sum([ 1 if x else 0 for x in results])/len(results):
#         print(grid)
#     return 1 == sum([ 1 if x else 0 for x in results])/len(results)
# def checknboxes(bxes,gryd):
#     grid = gryd.copy()
#     results = []
#     for box in bxes:
#         success = False
#         for location in open_positions_sorted(grid):
#             if checkvalid(box,location,grid):
#                 results.append(True)
#                 grid[location[0]:location[0]+len(box),location[1]:location[1]+len(box[0])] = box
#                 success = True
#                 break
#         if not success:
#             results.append(False)
#     if 1 == sum([ 1 if x else 0 for x in results])/len(results):
#         print(grid)
#     return 1 == sum([ 1 if x else 0 for x in results])/len(results) or checkboxes(rotlist(bxes),grid) or checkboxes(rotlist(bxes,2),grid) or checkboxes(rotlist(bxes,3),grid)
# # print(passTests)
# for test in failTests:
#     print(test)
#     array = np.array([[0]*test[1]]*test[0])
#     bs = []
#     for i, index in enumerate(test[2]):
#         bs += [boxes[i]] * index
#         # print(len([boxes[i]] * index))
#     # print(len(bs))
#     print(checknboxes(bs,array))


(4, 4, [0, 0, 0, 0, 2, 0], 2, 1)
[[1 1 1 0]
 [1 1 1 1]
 [1 1 0 1]
 [0 1 0 1]]
True
(12, 5, [1, 0, 1, 0, 2, 2], 6, 4)
[[1 1 1 0 0]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [0 0 1 1 0]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
True
(12, 5, [1, 0, 1, 0, 3, 2], 7, 4)
[[1 1 1 0 0]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [0 0 1 1 0]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
True
